name: Aspire Host build and push

on:
  push:
    branches: [ "main" ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          filter: tree:0
    
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
            dotnet-version: |
              9.0.x
              10.0.x
            include-prerelease: true
    
      - name: Restore dependencies
        run: dotnet restore
    
      - name: Build
        run: dotnet build --configuration Release --no-restore
    
      - name: Pack
        run: dotnet pack --configuration Release --no-build --output artifacts/
    
      - name: NuGet login (OIDC → temp API key)
        uses: NuGet/login@v1
        id: login
        with:
          user: albertomonteiro
    
      - name: NuGet push
        run: dotnet nuget push artifacts/*.nupkg --api-key ${{steps.login.outputs.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json --skip-duplicate